steps:

# Build Docker image
- name: gcr.io/cloud-builders/docker
  args:
    - build
    - -t
    - europe-west1-docker.pkg.dev/$PROJECT_ID/cloudbuild-images/webhook:$SHORT_SHA
    - ./webhook

# Push image
- name: gcr.io/cloud-builders/docker
  args:
    - push
    - europe-west1-docker.pkg.dev/$PROJECT_ID/cloudbuild-images/webhook:$SHORT_SHA

- name: gcr.io/google.com/cloudsdktool/cloud-sdk
  entrypoint: gcloud
  args:
    - container
    - clusters
    - get-credentials
    - $_CLUSTER
    - --zone=$_ZONE

# Deploy to Cloud Run (en nuestro lab; en el examen sería GKE)
- name: gcr.io/cloud-builders/gke-deploy
  args:
    - run
    - --cluster=$_CLUSTER
    - --location=$_ZONE

- name: curlimages/curl
  entrypoint: curl
  args:
    - -X
    - POST
    - $_WEBHOOK_URL
    - -H
    - Content-Type: application/json
    - -d
    - |
      {
        "project":"$PROJECT_ID",
        "build":"$BUILD_ID",
        "status":"SUCCESS",
        "image":"$SHORT_SHA"
      }
images:
  - europe-west1-docker.pkg.dev/$PROJECT_ID/cloudbuild-images/webhook:$SHORT_SHA
