options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _REGION: "europe-west1"
  _REPOSITORY: "cloudbuild-images"
  _IMAGE: "webhook"
  _IMAGE_TAG: "1.0.0"
  _CLUSTER: "cloudbuild-webhook-lab"
  _ZONE: "europe-west1-b"
  _NAMESPACE: "production"

steps:

# =========================
# BUILD IMAGE
# =========================
- name: gcr.io/cloud-builders/docker
  id: Build image
  args:
    - build
    - -t
    - europe-west1-docker.pkg.dev/$PROJECT_ID/$_REPOSITORY/$_IMAGE:$_IMAGE_TAG
    - ./webhook

# =========================
# PUSH IMAGE
# =========================
- name: gcr.io/cloud-builders/docker
  id: Push image
  args:
    - push
    - europe-west1-docker.pkg.dev/$PROJECT_ID/$_REPOSITORY/$_IMAGE:$_IMAGE_TAG

# =========================
# GET GKE CREDENTIALS
# =========================
- name: gcr.io/google.com/cloudsdktool/cloud-sdk
  id: Get cluster credentials
  entrypoint: gcloud
  args:
    - container
    - clusters
    - get-credentials
    - $_CLUSTER
    - --zone=$_ZONE
    - --project=$PROJECT_ID

# =========================
# DEPLOY TO GKE
# =========================
- name: gcr.io/cloud-builders/kubectl
  id: Deploy to GKE
  args:
    - apply
    - -f
    - k8s/
  env:
    - "CLOUDSDK_COMPUTE_ZONE=$_ZONE"
    - "CLOUDSDK_CONTAINER_CLUSTER=$_CLUSTER"

images:
  - europe-west1-docker.pkg.dev/$PROJECT_ID/$_REPOSITORY/$_IMAGE:$_IMAGE_TAG