steps:

# Build image
- name: gcr.io/cloud-builders/docker
  args:
    - build
    - -t
    - europe-west1-docker.pkg.dev/$PROJECT_ID/cloudbuild-images/webhook:$SHORT_SHA
    - ./webhook

# Push image
- name: gcr.io/cloud-builders/docker
  args:
    - push
    - europe-west1-docker.pkg.dev/$PROJECT_ID/cloudbuild-images/webhook:$SHORT_SHA

# Get GKE credentials
- name: gcr.io/google.com/cloudsdktool/cloud-sdk
  entrypoint: gcloud
  args:
    - container
    - clusters
    - get-credentials
    - $_CLUSTER
    - --zone=$_ZONE

# Deploy to GKE
- name: gcr.io/cloud-builders/gke-deploy
  args:
    - run
    - --filename=k8s.yaml
    - --cluster=$_CLUSTER
    - --location=$_ZONE

images:
  - europe-west1-docker.pkg.dev/$PROJECT_ID/cloudbuild-images/webhook:$SHORT_SHA
